---
- name: restart docker
  sudo: yes
  service:
    name: docker
    state: restarted

- name: restart collectd
  sudo: yes
  service:
    name: collectd
    state: restarted
  ignore_errors: yes

- name: restart rsyslog
  sudo: yes
  service:
    name: rsyslog
    state: restarted

- name: reload docker
  sudo: yes
  command: systemctl daemon-reload
  notify:
    - restart docker
