---
- name: centos | install docker packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-selinux
  tags:
    - docker
    - bootstrap

- name: centos | configure docker consul dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^OPTIONS=
    line: OPTIONS='--selinux-enabled --dns {{ private_ipv4 }} --dns-search service.{{ consul_dns_domain }} --log-driver=syslog'
    state: present
    create: yes
  notify:
    - restart docker
  tags:
    - docker