---
- name: upstream | install docker repo
  sudo: yes
  copy:
    src: docker.repo
    dest: /etc/yum.repos.d/docker.repo
  tags:
    - docker
    - bootstrap

- name: upstream | install docker packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-engine-1.7.0
    - docker-selinux
  tags:
    - docker
    - bootstrap

- name: upstream | configure docker consul dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^other_arg=
    line: other_arg='--dns {{ private_ipv4 }} --dns-search service.{{ consul_dns_domain }} --log-driver=syslog'
    state: present
    create: yes
  notify:
    - restart docker
  tags:
    - docker

- name: upstream | create docker.system.d
  sudo: yes
  file:
    dest: /etc/systemd/system/docker.service.d
    state: directory
  tags:
    - docker

- name: upstream | create local docker service override
  sudo: yes
  copy:
    dest: /etc/systemd/system/docker.service.d/local.conf
    content: |
      [Service]
      EnvironmentFile=-/etc/sysconfig/docker
      ExecStart=
      ExecStart=/usr/bin/docker -d -H fd:// $other_arg
  notify:
    - reload docker
  tags:
    - docker